input AddContentInput {
  file: Upload!
  workspaceId: String!
  tags: [String!]!
}

input DeleteContentInput {
  id: ID! @tag(validate: "mongodb")
}

input AddContentTagsInput {
  id: ID! @tag(validate: "mongodb")
  tags: [String!]! @tag(validate: "min=1,dive,required")
}

input RemoveContentTagsInput {
  id: ID! @tag(validate: "mongodb")
  tags: [String!]! @tag(validate: "min=1,dive,required")
}

input ReplaceContentTagsInput {
  id: ID! @tag(validate: "mongodb")
  tags: [String!]! @tag(validate: "dive,required")
}

input ModifyTagInput {
  old: String! @tag(validate: "required")
  new: String! @tag(validate: "required")
}

input ModifyContentTagsInput {
  id: ID! @tag(validate: "mongodb")
  tags: [ModifyTagInput!]! @tag(validate: "min=1,dive")
}

input ContentFilter {
  workspaceId: String @tag(validate: "required")
  ids: [String] @tag(validate: "omitempty,dive,required")
  tags: [String] @tag(validate: "omitempty,dive,required")
  # NOTE: とりあえずtagによる検索ができるように実装
  #       その他の情報による検索は必要に応じて追加する
  page: PaginationInput @tag(validate: "omitempty")
}

type Content {
  id: ID!
  workspaceId: String!
  presignedUrl: String!
  tags: [String!]!
  file: File!
  createdAt: String!
  updatedAt: String!
}

type File {
  name: String!
  extension: String!
  type: String!
  size: Int!
}

type ContentEdge {
  node: Content!
  cursor: String!
}

type ContentConnection {
  edges: [ContentEdge!]!
  pageInfo: PageInfo!
}

type ContentPayload {
  id: ID!
  workspaceId: String!
  tags: [String!]!
  file: FilePayload!
  createdAt: String!
  updatedAt: String!
}

type FilePayload {
  name: String!
  extension: String!
  type: String!
  size: Int!
}

extend type Mutation {
  addContent(input: AddContentInput!): ContentPayload!
  deleteContent(input: DeleteContentInput!): ContentPayload!
  addContentTags(input: AddContentTagsInput!): ContentPayload!
  removeContentTags(input: RemoveContentTagsInput!): ContentPayload!
  replaceContentTags(input: ReplaceContentTagsInput!): ContentPayload!
  modifyContentTags(input: ModifyContentTagsInput!): ContentPayload!
}

extend type Query {
  content(id: ID!): Content
  contents(filter: ContentFilter): ContentConnection
}
