extend type Query {
  # NOTE: relay connection の引数はトップレベルに配置すること（apollo clientのキャッシュ設定が面倒になるため）
  images(
    first: Int @tag(validate: "omitempty,min=1,max=100")
    last: Int @tag(validate: "omitempty,min=1,max=100")
    after: String @tag(validate: "omitempty,min=1")
    before: String @tag(validate: "omitempty,min=1")
    filter: ImagesFilterInput
  ): ImageConnection!
}

extend type Mutation {
  uploadImage(input: UploadImageInput!): UploadImagePayload!

  updateImage(input: UpdateImageInput!): UpdateImagePayload!
  updateImages(input: UpdateImagesInput!): UpdateImagesPayload!

  deleteImage(input: DeleteImageInput!): DeleteImagePayload!
  deleteImages(input: DeleteImagesInput!): DeleteImagesPayload!

  downloadImage(input: DownloadImageInput!): FileObject!
  downloadImages(input: DownloadImagesInput!): FileObject!
}

input ImagesFilterInput {
  tags: [String!] @tag(validate: "search_image_tags")
}

enum Visibility {
  PUBLIC
  PRIVATE
}

input UploadImageInput {
  file: Upload!
  tags: [String!]! @tag(validate: "input_image_tags")
  visibility: Visibility!
}

input UpdateImageInput {
  id: ID! @tag(validate: "ulid")
  tags: [String!]! @tag(validate: "input_image_tags")
}

input UpdateImagesInput {
  targets: [UpdateImageInput!]! @tag(validate: "dive,min=1,max=100")
}

input DeleteImageInput {
  id: ID! @tag(validate: "ulid")
}

input DeleteImagesInput {
  ids: [ID!]! @tag(validate: "dive,ulid,min=1,max=100")
}

input DownloadImageInput {
  id: ID! @tag(validate: "ulid")
}

input DownloadImagesInput {
  ids: [ID!]! @tag(validate: "dive,ulid,min=1,max=100")
}


# === payload ===
# NOTE: 対象情報の他に付属する情報を返却したいケースに対応するためPayloadという層を用意している
type UploadImagePayload {
  node: Image!
}

type UpdateImagePayload {
  node: Image!
}

type UpdateImagesPayload {
  nodes: [Image!]!
}

type DeleteImagePayload {
  id: ID!
}

type DeleteImagesPayload {
  ids: [ID!]!
}

# === domain model ===

type Image {
  id: ID!
  file: ImageFile!
  size: ImageSize!
  src: ImageSrc!
  tags: [String!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type ImageFile {
  name: String!
  size: Int!
}

type ImageSize {
  width: Int!
  height: Int!
}

type ImageSrc {
  thumbnail: String!
  preview: String!
}

# === shared model ===

type FileObject {
  url: String!
  name: String!
  expiresAt: DateTime!
  contentType: String!
}

# === relay model ===

type ImageEdge {
  node: Image!
  cursor: String!
}

type ImageConnection {
  edges: [ImageEdge!]!
  pageInfo: PageInfo!
}
