extend type Query {
  # NOTE: relay connection の引数はトップレベルに配置すること（apollo clientのキャッシュ設定が面倒になるため）
  images(
    first: Int @tag(validate: "omitempty,min=1,max=100")
    last: Int @tag(validate: "omitempty,min=1,max=100")
    after: String @tag(validate: "omitempty,min=1")
    before: String @tag(validate: "omitempty,min=1")
    filter: ImagesFilterInput
  ): ImageConnection!
}

extend type Mutation {
  uploadImage(input: UploadImageInput!): UploadImagePayload!

  updateImage(input: UpdateImageInput!): UpdateImagePayload!
  updateImages(input: UpdateImagesInput!): UpdateImagesPayload!

  deleteImage(input: DeleteImageInput!): DeleteImagePayload!
  deleteImages(input: DeleteImagesInput!): DeleteImagesPayload!

  downloadImage(input: DownloadImageInput!): DownloadUrl!
  downloadImages(input: DownloadImagesInput!): DownloadUrl!
}

input ImagesFilterInput {
  tags: [String!]
}

enum Visibility {
  PUBLIC
  PRIVATE
}

input UploadImageInput {
  file: Upload!
  tags: [String!]!
  visibility: Visibility!
}

input UpdateImageInput {
  id: ID!
  tags: [String!]!
}

input UpdateImagesInput {
  targets: [UpdateImageInput!]!
}

input DeleteImageInput {
  id: ID!
}

input DeleteImagesInput {
  ids: [ID!]!
}

input DownloadImageInput {
  id: ID!
}

input DownloadImagesInput {
  ids: [ID!]!
}


# === payload ===

type UploadImagePayload {
  id: ID!
}

type UpdateImagePayload {
  id: ID!
}

type UpdateImagesPayload {
  ids: [ID!]!
}

type DeleteImagePayload {
  id: ID!
}

type DeleteImagesPayload {
  ids: [ID!]!
}

# === domain model ===

type Image {
  id: ID!
  info: ImageInfo!
  src: ImageSrc!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type ImageInfo {
  file: ImageFile!
  size: ImageSize!
  tags: [String!]!
}

type ImageFile {
  name: String!
  size: Int!
}

type ImageSize {
  width: Int!
  height: Int!
}

type ImageSrc {
  thumbnail: String!
  preview: String!
}

# === shared model ===

type DownloadUrl {
  url: String!
  expiresAt: DateTime!
  fileName: String!
  contentType: String!
}

# === relay model ===

type ImageEdge {
  node: Image!
  cursor: String!
}

type ImageConnection {
  edges: [ImageEdge!]!
  pageInfo: PageInfo!
}
