extend type Query {
  viewer: Viewer!
}

enum FileType {
  JPG
  PNG
}

type Viewer {
  id: ID!
  limit: Limit!
  usage: Usage!
}

type Limit {
  upload: UploadLimit!
}

type Usage {
  storage: StorageUsage!
  fileStats: FileStats!
}

type UploadLimit {
  maxCount: Int!
  maxSize: Int!
  allowedFileType: [FileType!]!
}

type StorageUsage {
  used: Int!
  total: Int!
}

type FileStats {
  totalCount: Int!
  totalSize: Int!
  byType: [FileTypeStats!]!
}

type FileTypeStats {
  fileType: FileType!
  fileCount: Int!
  fileSize: Int!
}
