query GetImageGroups(
  $first: Int
  $last: Int
  $after: String
  $before: String
  $filter: ImageGroupsFilterInput
)  {
  imageGroups(
    first: $first
    last: $last
    after: $after
    before: $before
    filter: $filter
  ) {
    edges {
      cursor
      node {
        id
        name
        count
        thumbnails
        createdAt
        updatedAt
      }
    }
    pageInfo {
      hasNextPage
      hasPrevPage
      endCursor
      startCursor
    }
  }
}


query GetImageGroup(
  $first: Int
  $last: Int
  $after: String
  $before: String
  $filter: ImageGroupInput!) {
  imageGroup(input: $filter) {
      id
      name
      count
    	images(
        first: $first
        last: $last
        after: $after
        before: $before
      ) {
      	edges {
          cursor
          node {
            id
            file {
              size
              name
            }
            size {
              height
              width
            }
            src {
              thumbnail
              preview
            }
            tags
          }
        }
      	pageInfo {
          hasNextPage
          hasPrevPage
          endCursor
          startCursor
        }
    	}
      createdAt
      updatedAt
  }
}

mutation CreateImageGroup($input: CreateImageGroupInput!) {
  createImageGroup(input: $input) {
    node {
      id
      name
      count
      thumbnails
      createdAt
      updatedAt
    }
  }
}

mutation UpdateImageGroup($input: UpdateImageGroupInput!) {
  updateImageGroup(input: $input) {
    node {
      id
      name
      count
      thumbnails
      createdAt
      updatedAt
    }
  }
}

mutation DeleteImageGroup($input: DeleteImageGroupInput!) {
  deleteImageGroup(input: $input) {
    id
  }
}

