mutation UploadImage($input: UploadImageInput!) {
  uploadImage(input: $input) {
    node {
      id
    }
  }
}


mutation UpdateImage($input: UpdateImageInput!) {
  updateImage(input: $input) {
    node {
      id
    }
  }
}


mutation DeleteImage($input: DeleteImageInput!) {
  deleteImage(input: $input) {
    id
  }
}


mutation DeleteImages($input: DeleteImagesInput!) {
  deleteImages(input: $input) {
    ids
  }
}


mutation DownloadImage($input: DownloadImageInput!) {
  downloadImage(input: $input) {
    url
    name
    expiresAt
    contentType
  }
}


mutation DownloadImages($input: DownloadImagesInput!) {
  downloadImages(input: $input) {
    url
    name
    expiresAt
    contentType
  }
}


query GetImage($id: ID!) {
  image(id: $id) {
    ...ImageFields
  }
}

query GetImages(
  $first: Int
  $last: Int
  $after: String
  $before: String
  $filter: ImagesFilterInput
) {
  images(
    first: $first
    last: $last
    after: $after
    before: $before
    filter: $filter
  ) {
    edges {
      node {
        ...ImageFields
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPrevPage
      startCursor
      endCursor
    }
  }
}

query GetEditImages($ids: [ID!]!) {
  imagesByIds(ids: $ids) {
    id
    file {
      name
      size
    }
    tags
    src {
      thumbnail
    }
  }
}
