query GetMe {
  me {
    id
    limit {
      upload {
        file {
          count
          size
          type
        }
        tag {
          count
        }
      }
    }
    preference {
      file {
      dateFormat
      fileSizeUnit
      }
      thumbnail {
        size
        spacing
      }
      preview {
        loop
        show
      }
    }
    createdAt
    updatedAt
  }
}

query GetProfile {
  me {
    id
    profile {
      name
      email
    }
    createdAt
    updatedAt
  }
}

mutation UpdateProfile($input: UpdateProfileInput!) {
  updateProfile(input: $input) {
    id
    profile {
      name
      email
    }
    createdAt
    updatedAt
  }
}


query GetPreference {
  me {
    id
    preference {
      file {
      dateFormat
      fileSizeUnit
      }
      thumbnail {
        size
        spacing
      }
      preview {
        loop
        show
      }
    }
    createdAt
    updatedAt
  }
}

mutation UpdatePreference($input: UpdatePreferenceInput!) {
  updatePreference(input: $input) {
    file {
      dateFormat
      fileSizeUnit
    }
    thumbnail {
      size
      spacing
    }
    preview {
      loop
      show
    }
  }
}

query GetUsage {
  me {
    id
  	limit {
      upload {
        file {
          count
          size
          type
        }
        tag {
          count
        }
      }
    }
    usage {
      storage {
      	used
      	total
    	}
      fileStats {
        totalCount
        totalSize
        byType {
          fileType
          fileCount
          fileSize
        }
      }
    }
  }
}
