query GetMe {
  me {
    id
    createdAt
    updatedAt
  }
}

query GetUserProfile {
  me {
    id
    profile {
      name
      email
    }
    createdAt
    updatedAt
  }
}

mutation UpdateProfile($input: UpdateProfile!) {
  updateProfile(input: $input) {
    id
    profile {
      name
      email
    }
    createdAt
    updatedAt
  }
}

query GetUserUsage {
  viewer {
    id
  	limit {
      upload {
        maxCount
        maxSize
        allowedFileType
      }
    }
    usage {
      storage {
      	used
      	total
    	}
      fileStats {
        totalCount
        totalSize
        byType {
          fileType
          fileCount
          fileSize
        }
      }
    }
  }
}
