import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import React from "react";
import { ApolloProvider, ThemeProvider } from "@/component/containers";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Props = React.PropsWithChildren<{
	children: React.ReactNode;
}>;

const RootLayout: React.FC<Props> = ({ children }) => (
	<html lang="en">
		<ThemeProvider>
			<body className={inter.className}>
				<AntdRegistry>
					<ApolloProvider>{children}</ApolloProvider>
				</AntdRegistry>
			</body>
		</ThemeProvider>
	</html>
);

export default RootLayout;
export { metadata };
