import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Body } from "./_component";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Props = React.PropsWithChildren<{
	children: React.ReactNode;
}>;

const RootLayout: React.FC<Props> = ({ children }) => (
	<html lang="en">
		<Body className={inter.className}>
			<AntdRegistry>{children}</AntdRegistry>
		</Body>
	</html>
);

export default RootLayout;
export { metadata };
