import type { Metadata } from "next";
import { FC } from "react";

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Props = {
	children: React.ReactNode;
};

const Layout: FC<Props> = (props) => {
	const { children } = props;
	return <div>{children}</div>;
};

export default Layout;
export { metadata };
